name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb4ea8b52298a8d861f562bd4bd2b1d9e92fa34bdfe9338744e6d634fbf1c08b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
