name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c281f8c0c1654534123e6da6608c932313fae8e1153992de675cd26cb25a80eb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
