name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6c4455d1824d1dbf6e19368b6acba9e25299bf2ffb5696a8c98cde5ac43cca7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
