name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af164e08c0126ca564e43709be1240444e250a6e289fbeb391d1115a960ff30e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
