name = "Dartis-Craft - Kakusei 2 Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5cc5736806a392bcc12135cfbd144949a0d861caf5b78f30ba839fa241b1e0f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
